apiVersion: v1
kind: Template
metadata:
  labels:
    name: spark-driver
  name: spark-driver
objects:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        name: spark-driver
      name: spark-driver
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            name: spark-driver
        spec:
          containers:
          - image: enmasseproject/spark-driver:1.0-SNAPSHOT
            name: spark-driver
            env:
              - name: SPARK_MASTER_HOST
                value: ${SPARK_MASTER_HOST}
              - name: SPARK_MASTER_PORT
                value: ${SPARK_MASTER_PORT}
              - name: SPARK_DRIVER_USERNAME
                value: ${SPARK_DRIVER_USERNAME}
              - name: SPARK_DRIVER_PASSWORD
                value: ${SPARK_DRIVER_PASSWORD}
parameters:
  - description: Spark Master node IP address
    name: SPARK_MASTER_HOST
    required: true
  - description: Spark Master node port
    name: SPARK_MASTER_PORT
    value: "7077"
    required: true
  - description: Username for EnMasse authentication
    name: SPARK_DRIVER_USERNAME
  - description: Password for EnMasse authentication
    name: SPARK_DRIVER_PASSWORD
